resources:
  - base/Central-Station.yaml
  - base/Elasticsearch.yaml
  - base/Expiry-Processor.yaml
  - base/Kafka.yaml
  - base/OpenMeteo-Producer.yaml
  - base/Rain-Processor.yaml
  - base/Weather-Station.yaml