apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: central-station-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-station
  labels:
    app: central-station
spec:
  selector:
    matchLabels:
      app: central-station
  template:
    metadata:
      labels:
        app: central-station
    spec:
      containers:
        - name: central-station
          image: mostafagalal1/central-station:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: storage
              mountPath: /app/data      # Path inside container where volume will be mounted
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: central-station-pvc