---
apiVersion: v1
kind: Service
metadata:
  name: central-station-service
  labels:
    app: central-station
spec:
  type: NodePort
  selector:
    app: central-station
  ports:
    - name: central-station-port
      port: 8080
      targetPort: 8080
      nodePort: 30080  # NodePort for external access, can be any port in the range 30000-32767

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: central-station-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-station
  labels:
    app: central-station
spec:
  selector:
    matchLabels:
      app: central-station
  template:
    metadata:
      labels:
        app: central-station
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox
          command: [ 'sh', '-c', 'until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done' ]
      containers:
        - name: central-station
          image: mostafagalal1/central-station:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: storage
              mountPath: /app/data      # Path inside container where volume will be mounted
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: central-station-pvc