apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-kibana-parquet-python-service
spec:
  type: LoadBalancer
  selector:
    app: elasticsearch-kibana-parquet-python
  ports:
    - name: elasticsearch
      port: 9200
      targetPort: 9200
    - name: kibana
      port: 5601
      targetPort: 5601

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-kibana-parquet-python
  labels:
    app: elasticsearch-kibana-parquet-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-kibana-parquet-python
  template:
    metadata:
      labels:
        app: elasticsearch-kibana-parquet-python
    spec:
      containers:
        - name: elasticsearch-kibana
          image: nshou/elasticsearch-kibana
          ports:
            - name: elasticsearch
              containerPort: 9200
            - name: kibana
              containerPort: 5601
          env:
            - name: SSL_MODE
              value: "false"

        - name: parquet-to-elasticsearch-python
          image: mostafagalal1/parquet-to-elasticsearch-python:latest
          volumeMounts:
            - name: shared-storage
              mountPath: /data

      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: central-station-pvc
