---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiry-processor            # Name of the Deployment resource
  labels:
    app: expiry-processor           # Label for identifying the Deployment
spec:
  selector:
    matchLabels:
      app: expiry-processor         # Matches pods with this label to manage them
  template:
    metadata:
      labels:
        app: expiry-processor       # Labels assigned to pods created by this Deployment
    spec:
      containers:
        - name: expiry-processor    # Name of the container
          image: mostafagalal1/expiry-processor   # Container image (should be accessible in your image registry)
          ports:
            - containerPort: 8080 # Port exposed by the container
