---
apiVersion: v1
kind: Service
metadata:
  name: kafka                  # Service name, used by the StatefulSet for stable DNS
  labels:
    app: kafka                 # Label for identifying the service
spec:
  clusterIP: None              # Makes this a headless service (no load balancing or cluster IP)
  selector:
    app: kafka                 # Selects pods with this label
  ports:
    - name: broker             # Named port for Kafka broker
      port: 9092               # Exposes port 9092 on the service

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka                  # Name of the StatefulSet
  labels:
    app: kafka                 # Label for identifying the StatefulSet
spec:
  serviceName: kafka           # Refers to the headless service for stable network identity
  replicas: 3                  # Number of Kafka replicas (brokers)
  selector:
    matchLabels:
      app: kafka               # Matches pods with this label
  template:
    metadata:
      labels:
        app: kafka             # Labels applied to the pod template
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          env:                              # Kafka configuration via env variables
            - name: HOSTNAME
              valueFrom:
                  fieldRef:
                    fieldPath: metadata.name  # Node ID is the pod name
            - name: KAFKA_CLUSTER_ID
              value: "kafka-cluster"       # Cluster ID for Kafka
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"    # Roles assigned to this node
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"  # Listener configuration
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"  # Security protocols for listeners
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"           # Listener name for controller
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"            # Listener for inter-broker communication
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka-0.kafka:9093, 1@kafka-1.kafka:9093, 2@kafka-2.kafka:9093" # Quorum voters (KRaft mode) with stable DNS of pod
            - name: KAFKA_KRAFT_MODE
              value: "true"                 # Enables KRaft mode (no Zookeeper)
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"                # Disable auto-creation of topics
          command:
            - sh
            - -c
            - |
              ORDINAL=${HOSTNAME##*-}
              export KAFKA_CFG_NODE_ID="$ORDINAL"
              exec /opt/bitnami/scripts/kafka/entrypoint.sh /opt/bitnami/scripts/kafka/run.sh
          ports:
            - name: broker
              containerPort: 9092          # Kafka broker port
            - name: controller
              containerPort: 9093          # Kafka controller port
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka    # Mount path for Kafka persistent data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]     # Only one node can mount this PVC at a time
        resources:
          requests:
            storage: 2Gi                   # Request 2Gi of storage per Kafka pod
