---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rain-processor            # Name of the Deployment resource
  labels:
    app: rain-processor           # Label for identifying the Deployment
spec:
  selector:
    matchLabels:
      app: rain-processor         # Matches pods with this label to manage them
  template:
    metadata:
      labels:
        app: rain-processor       # Labels assigned to pods created by this Deployment
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox
          command: [ 'sh', '-c', 'until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done' ]
      containers:
        - name: rain-processor    # Name of the container
          image: mostafagalal1/rain-processor:latest   # Container image (should be accessible in your image registry)
          ports:
            - containerPort: 8080 # Port exposed by the container
