---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rain-processor            # Name of the Deployment resource
  labels:
    app: rain-processor           # Label for identifying the Deployment
spec:
  selector:
    matchLabels:
      app: rain-processor         # Matches pods with this label to manage them
  template:
    metadata:
      labels:
        app: rain-processor       # Labels assigned to pods created by this Deployment
    spec:
      containers:
        - name: rain-processor    # Name of the container
          image: mostafagalal1/rain-processor   # Container image (should be accessible in your image registry)
          ports:
            - containerPort: 8080 # Port exposed by the container
