name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up JDK 20 for both projects
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven

    # Build Rain-Processor Maven project
    - name: Build Rain-Processor with Maven
      run: mvn -B package --file Rain-Processor/pom.xml

    # Build Weather-Station Maven project
    - name: Build Weather-Station with Maven
      run: mvn -B package --file Weather-Station/pom.xml
